name:                Testing
version:             0.1.0.0
github:              "keith_harrison/Testing"
license:             BSD3
author:              "Keith Harrison"
maintainer:          "kh530@exeter.ac.uk"
copyright:           "2022 keith harrison"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Testing#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers
- generic-random
library:
  source-dirs: src

executables:
  Testing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Testing

tests:
  Testing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Testing
